<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Stadt',
    'Country' => 'Land',
    'Create New Location' => 'Neuen Ort erstellen',
    'Create locations' => 'Orte erstellen',
    'Delete Location' => 'Ort löschen',
    'Delete locations' => 'Orte löschen',
    'District' => 'Distrikt',
    'Edit Location' => 'Ort bearbeiten',
    'Formatted address' => 'Formatierte Adresse',
    'House number' => 'Hausnummer',
    'Latitude' => 'Breitengrad',
    'Location' => 'Ort',
    'Locations' => 'Orte',
    'Longitude' => 'Längengrad',
    'Name' => 'Name',
    'New Location' => 'Neuer Ort',
    'Postal code' => 'Postleitzahl',
    'Provider ID' => 'Anbieter-ID',
    'Search for a location ...' => 'Nach einem Ort suchen ...',
    'State' => 'Bundesland',
    'Street' => 'Straße',
    'The location was created.' => 'Der Ort wurde erstellt.',
    'The location was deleted.' => 'Der Ort wurde gelöscht.',
    'The location was updated.' => 'Der Ort wurde aktualisiert.',
    'Unnamed' => 'Unbenannt',
    'Update locations' => 'Orte aktualisieren',
];
