<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => '',
    'City' => '',
    'Country' => '',
    'Create New Location' => '',
    'Create New Tag' => '',
    'Create location tags' => '',
    'Create locations' => '',
    'Delete Location' => '',
    'Delete Tag' => '',
    'Delete location tags' => '',
    'Delete locations' => '',
    'District' => '',
    'Edit Location' => '',
    'Edit Tag' => '',
    'Formatted address' => '',
    'House number' => '',
    'Latitude' => '',
    'Location' => '',
    'Locations' => '',
    'Location–Tag' => '',
    'Longitude' => '',
    'Name' => '',
    'New Location' => '',
    'New Tag' => '',
    'Postal code' => '',
    'Provider ID' => '',
    'Search for a location ...' => '',
    'State' => '',
    'Street' => '',
    'Tag' => '',
    'Tags' => '',
    'The location was created.' => '',
    'The location was deleted.' => '',
    'The location was updated.' => '',
    'The tag was added to the location.' => '',
    'The tag was created.' => '',
    'The tag was deleted.' => '',
    'The tag was removed to the location.' => '',
    'The tag was updated.' => '',
    'Unnamed' => '',
    'Update location tags' => '',
    'Update locations' => '',
];
