<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Hinzugefügt',
    'City' => 'Stadt',
    'Country' => 'Land',
    'Create New Location' => 'Neuen Ort erstellen',
    'Create New Tag' => 'Neues Tag erstellen',
    'Create location tags' => 'Neue Ort-Tags erstellen',
    'Create locations' => 'Orte erstellen',
    'Delete Location' => 'Ort löschen',
    'Delete Tag' => 'Tag löschen',
    'Delete location tags' => 'Ort-Tags löschen',
    'Delete locations' => 'Orte löschen',
    'District' => 'Distrikt',
    'Edit Location' => 'Ort bearbeiten',
    'Edit Tag' => 'Tag bearbeiten',
    'Formatted address' => 'Formatierte Adresse',
    'House number' => 'Hausnummer',
    'Latitude' => 'Breitengrad',
    'Location' => 'Ort',
    'Locations' => 'Orte',
    'Location–Tag' => 'Ort–Tag',
    'Longitude' => 'Längengrad',
    'Name' => 'Name',
    'New Location' => 'Neuer Ort',
    'New Tag' => 'Neues Tag',
    'Postal code' => 'Postleitzahl',
    'Provider ID' => 'Anbieter-ID',
    'Search for a location ...' => 'Nach einem Ort suchen ...',
    'State' => 'Bundesland',
    'Street' => 'Straße',
    'Tag' => 'Tag',
    'Tags' => 'Tags',
    'The location was created.' => 'Der Ort wurde erstellt.',
    'The location was deleted.' => 'Der Ort wurde gelöscht.',
    'The location was updated.' => 'Der Ort wurde aktualisiert.',
    'The tag was added to the location.' => 'Das Tag wurde dem Ort hinzugefügt.',
    'The tag was created.' => 'Das Tag wurde erstellt.',
    'The tag was deleted.' => 'Das Tag wurde gelöscht.',
    'The tag was removed to the location.' => 'Das Tag wurde vom Ort entfernt.',
    'The tag was updated.' => 'Das Tag wurde aktualisiert.',
    'Unnamed' => 'Unbenannt',
    'Update location tags' => 'Ort-Tags aktualisieren',
    'Update locations' => 'Orte aktualisieren',
];
