<?php

declare(strict_types=1);

namespace Hirtz\Location\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000700LocationBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            CREATE TABLE `location` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` smallint(6) NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `name` varchar(255) DEFAULT NULL,
              `formatted_address` varchar(255) DEFAULT NULL,
              `street` varchar(255) DEFAULT NULL,
              `house_number` varchar(255) DEFAULT NULL,
              `locality` varchar(255) DEFAULT NULL,
              `postal_code` varchar(255) DEFAULT NULL,
              `district` varchar(255) DEFAULT NULL,
              `state` varchar(255) DEFAULT NULL,
              `country_code` varchar(2) DEFAULT NULL,
              `lat` decimal(10,8) DEFAULT NULL,
              `lng` decimal(11,8) DEFAULT NULL,
              `provider_id` text DEFAULT NULL,
              `tag_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tag_ids`)),
              `tag_count` int(11) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              PRIMARY KEY (`id`),
              KEY `name` (`name`,`status`,`type`),
              KEY `formatted_address` (`formatted_address`,`status`,`type`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `tag` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` smallint(6) NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `name` varchar(255) NOT NULL,
              `location_count` int(11) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              PRIMARY KEY (`id`),
              UNIQUE KEY `name` (`name`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `location_tag` (
              `location_id` int(11) unsigned NOT NULL,
              `tag_id` int(11) unsigned NOT NULL,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              PRIMARY KEY (`location_id`,`tag_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
